# Generated by Django 5.2.1 on 2025-09-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('prazo', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
